  Armor:
    - "LEATHER_HELMET"
    - "LEATHER_CHESTPLATE"
    - "LEATHER_LEGGINGS"
    - "LEATHER_BOOTS"
    - "CHAINMAIL_HELMET"
    - "CHAINMAIL_CHESTPLATE"
    - "CHAINMAIL_LEGGINGS"
    - "CHAINMAIL_BOOTS"
    - "IRON_HELMET"
    - "IRON_CHESTPLATE"
    - "IRON_LEGGINGS"
    - "IRON_BOOTS"
    - "GOLDEN_HELMET"
    - "GOLD_CHESTPLATE"
    - "GOLDEN_LEGGINGS"
    - "GOLDEN_BOOTS"
    - "DIAMOND_HELMET"
    - "DIAMOND_CHESTPLATE"
    - "DIAMOND_LEGGINGS"
    - "DIAMOND_BOOTS"
    - "NETHERITE_HELMET"
    - "NETHERITE_CHESTPLATE"
    - "NETHERITE_LEGGINGS"
    - "NETHERITE_BOOTS"